name: Deploy-Dev

on:
    push:
        branches:
            - dev-front
            - dev

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                # --- GitHub Secrets Credentials ---
                host: ${{ secrets.PORTFOLIO_FRONT_DEV_SSH_HOST }}
                username: ${{ secrets.PORTFOLIO_FRONT_DEV_SSH_USERNAME }}
                password: ${{ secrets.PORTFOLIO_FRONT_DEV_SSH_PASSWORD }}

                script: |
                    PARENT_DIR="${{ secrets.PORTFOLIO_FRONT_DEV_SSH_PARENT_DIR }}"
                    PROJECT_NAME="${{ secrets.PORTFOLIO_FRONT_DEV_SSH_PROJECT_NAME }}"

                    cd $PARENT_DIR

                    echo "Running deployment phase..."

                    cd $PROJECT_NAME

                    git fetch
                    git pull origin dev-front
                    
                    echo "PULL successful."

                    cd ..
                    
                    echo "CI/CD SSH Completed!"