name: Deploy-Dev-Test

on:
    push:
        branches:
            - dev-front

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1.0.3
              with:
                # --- GitHub Secrets Credentials ---
                host: ${{ secrets.PORTFOLIO_FRONT_DEV_SSH_HOST }}
                username: ${{ secrets.PORTFOLIO_FRONT_DEV_SSH_USERNAME }}
                password: ${{ secrets.PORTFOLIO_FRONT_DEV_SSH_PASSWORD }}

                script: |
                    PARENT_DIR="${{ secrets.PORTFOLIO_FRONT_DEV_SSH_PARENT_DIR }}"
                    PROJECT_NAME="${{ secrets.PORTFOLIO_FRONT_DEV_SSH_PROJECT_NAME }}"

                    cd $PARENT_DIR

                    echo "Running deployment phase..."

                    cd $PROJECT_NAME

                    git fetch
                    git pull origin dev-front
                    
                    echo "PULL successful."

                    echo "Running npm install and build script..."

                    npm install --platform=linux --arch=x64
                    npm run build

                    echo "Build successful."

                    echo "Running server with pm2..."

                    cd ..

                    npx pm2 restart portfolio-dev-test

                    echo "CI/CD SSH Completed!"