name: CD-Liara
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_DEPLOY }}
        run: |
          npm i -g @liara/cli@5
          liara deploy --app="maziyar-portfolio" --api-token="$LIARA_DEPLOY" --no-app-logs --port=3000